- src/main/scala/ScalatraBootstrap.scala
Fix for lifecycle startup problems
> Move ScalatraBootstrap to top package so lifecycles are visible :shrug:

- pom.xml
- src/main/scala/com/ubirch/Binder.scala
- src/main/scala/com/ubirch/ConfPaths.scala
- src/main/scala/com/ubirch/Service.scala
- src/main/scala/com/ubirch/db/FlywayProvider.scala
tests should be added
this is only a quick fix
> adding automatic migration

- src/main/scala/com/ubirch/services/auth/AESEncryption.scala
- src/main/scala/com/ubirch/services/auth/AESKeyProvider.scala
adding a log for debugging -> MUST become deleted again.
> applying scalafmt formatting to remaining classes

- src/main/scala/com/ubirch/services/auth/AESKeyProvider.scala
> deletion of log that was only added for short term debugging

- src/main/scala/com/ubirch/Service.scala
- src/main/scala/com/ubirch/services/auth/AESEncryption.scala
Use BC for AES encryption/decryption
> UNG-2133 - adding BouncyCastle as provider and using it in AESEncryption

- src/main/scala/com/ubirch/controllers/TenantAdminController.scala
fixing tenant database entry retrieval mechanism
> using a different mechanism to query tenant from database

- src/main/resources/application-docker.conf
- src/main/resources/application.base.conf
- src/main/scala/com/ubirch/Binder.scala
- src/main/scala/com/ubirch/ConfPaths.scala
- src/main/scala/com/ubirch/Service.scala
- src/main/scala/com/ubirch/services/poc/PocCreationLoop.scala
- src/main/scala/com/ubirch/services/poc/PocCreator.scala
- src/test/resources/application.conf
- src/test/scala/com/ubirch/services/poc/PocCreationLoopTest.scala
- src/test/scala/com/ubirch/services/poc/PocCreatorTest.scala
- src/test/scala/com/ubirch/services/poc/PocTestHelper.scala
Reverts ubirch/ubirch-poc-manager#36
> Revert "Revert "a first draft of PocCreationLoop""

- src/main/scala/com/ubirch/controllers/SuperAdminController.scala
- src/main/scala/com/ubirch/controllers/TenantAdminController.scala
- src/test/scala/com/ubirch/InjectorHelperImpl.scala
- src/test/scala/com/ubirch/e2e/controllers/SuperAdminControllerSpec.scala
Controllers should use Users instead Device Keycloak
> UNG-2184 - Change Keycloak instance in Controllers to Users one

- src/main/resources/db/migration/V1_0__test_migration.sql
- src/main/scala/com/ubirch/controllers/SuperAdminController.scala
- src/main/scala/com/ubirch/services/superadmin/TenantService.scala
- src/test/scala/com/ubirch/e2e/controllers/SuperAdminControllerSpec.scala
Add constraint on tenant table
> UNG-2183 - constraint on tenant table for tenant_name uniqueness

- src/main/resources/db/migration/V1_0__test_migration.sql
- src/main/scala/com/ubirch/Binder.scala
- src/main/scala/com/ubirch/models/keycloak/user/UserException.scala
- src/main/scala/com/ubirch/models/poc/PocStatus.scala
- src/main/scala/com/ubirch/services/keycloak/groups/DefaultKeycloakGroupService.scala
- src/main/scala/com/ubirch/services/keycloak/users/KeycloakUserService.scala
- src/main/scala/com/ubirch/services/poc/DeviceCreator.scala
- src/main/scala/com/ubirch/services/poc/DeviceHelper.scala
- src/main/scala/com/ubirch/services/poc/PocCreator.scala
- src/test/scala/com/ubirch/ModelCreationHelper.scala
- src/test/scala/com/ubirch/e2e/keycloak/KeycloakIntegrationTest.scala
- src/test/scala/com/ubirch/services/keycloak/groups/TestKeycloakGroupsService.scala
- src/test/scala/com/ubirch/services/keycloak/users/TestKeycloakUserService.scala
- src/test/scala/com/ubirch/services/poc/PocCreatorTest.scala
> UNG-2276 add required groups to device

- src/main/scala/com/ubirch/util/AuditLogging.scala
> UNG-2058 Adding Audit Logging Helper

- pom.xml
Updates to newer Jetty version
> UNG-2230 Updating jetty version

- src/main/scala/com/ubirch/services/poc/CertHandler.scala
- src/main/scala/com/ubirch/services/superadmin/SuperAdminService.scala
> adding header and conflict handling of cert-manager

- src/main/scala/com/ubirch/controllers/TenantAdminController.scala
- src/main/scala/com/ubirch/services/tenantadmin/TenantAdminService.scala
- src/test/scala/com/ubirch/e2e/controllers/TenantAdminControllerSpec.scala
conflict will be returned and already existing web-initiate id
> add functionality to reject second initiation of web ident process

- src/main/scala/com/ubirch/controllers/PocAdminController.scala
- src/main/scala/com/ubirch/services/poc/employee/CsvProcessPocEmployee.scala
- src/test/scala/com/ubirch/InjectorHelperImpl.scala
- src/test/scala/com/ubirch/e2e/controllers/PocAdminControllerSpec.scala
- src/test/scala/com/ubirch/services/poc/employee/CsvProcessPocEmployeeTest.scala
Tests for create employees from CSV
> UNG-2140 - Tests for create employees from CSV

- src/main/scala/com/ubirch/models/auth/CertIdentifier.scala
- src/main/scala/com/ubirch/services/poc/PoCCertCreator.scala
- src/main/scala/com/ubirch/services/poc/PocAdminCreator.scala
- src/test/scala/com/ubirch/services/poc/PocAdminCreatorLoopTest.scala
- src/test/scala/com/ubirch/services/poc/PocAdminCreatorTest.scala
- src/test/scala/com/ubirch/services/poc/PocTestHelper.scala
and adding check to poc-admin creation that poc is completed, before admin is being created
> fixing cert textual identifier

- src/main/scala/com/ubirch/services/superadmin/SuperAdminService.scala
> fixing tenant-cert identifiers

- src/main/scala/com/ubirch/services/poc/InformationProvider.scala
- src/main/scala/com/ubirch/services/poc/parsers/PocAdminCsvParser.scala
- src/main/scala/com/ubirch/services/poc/parsers/PocCsvParser.scala
- src/main/scala/com/ubirch/services/poc/util/ValidatorConstants.scala
- src/main/scala/com/ubirch/services/util/Validator.scala
- src/test/scala/com/ubirch/services/poc/InformationProviderSpec.scala
- src/test/scala/com/ubirch/services/poc/parsers/PocAdminCsvParserTest.scala
- src/test/scala/com/ubirch/testutils/CentralCsvProvider.scala
- src/test/scala/com/ubirch/util/ValidatorTest.scala
and validation for expected json if tenantType == BMG
> adding pocType and jsonConfig field to certifyApi request

- src/main/scala/com/ubirch/models/auth/CertIdentifier.scala
- src/main/scala/com/ubirch/services/poc/PoCCertCreator.scala
> hot-fix/trimming names in cert textual identifiers

- src/main/scala/com/ubirch/controllers/PocAdminController.scala
- src/main/scala/com/ubirch/controllers/model/PocAdminControllerJsonModel.scala
- src/main/scala/com/ubirch/controllers/validator/PocEmployeeInValidator.scala
- src/main/scala/com/ubirch/services/keycloak/users/KeycloakUserService.scala
- src/main/scala/com/ubirch/services/pocadmin/PocAdminService.scala
- src/test/scala/com/ubirch/ModelCreationHelper.scala
- src/test/scala/com/ubirch/e2e/E2ETestBase.scala
- src/test/scala/com/ubirch/e2e/controllers/ControllerSpecHelper.scala
- src/test/scala/com/ubirch/e2e/controllers/PocAdminControllerSpec.scala
- src/test/scala/com/ubirch/e2e/controllers/SuperAdminControllerSpec.scala
- src/test/scala/com/ubirch/services/keycloak/users/TestKeycloakUserService.scala
Needs to be merge after https://github.com/ubirch/ubirch-poc-manager/pull/158
> UNG-2146 Update PocEmployee

- src/main/scala/com/ubirch/Service.scala
- src/main/scala/com/ubirch/controllers/HealthChecksController.scala
- src/main/scala/com/ubirch/db/tables/PocAdminTable.scala
- src/main/scala/com/ubirch/db/tables/PocEmployeeTable.scala
- src/main/scala/com/ubirch/db/tables/PocTable.scala
- src/main/scala/com/ubirch/services/poc/PocAdminCreationLoop.scala
- src/main/scala/com/ubirch/services/poc/PocAdminCreator.scala
- src/main/scala/com/ubirch/services/poc/PocCreationLoop.scala
- src/main/scala/com/ubirch/services/poc/PocCreator.scala
- src/main/scala/com/ubirch/services/poc/PocEmployeeCreationLoop.scala
- src/main/scala/com/ubirch/services/poc/PocEmployeeCreator.scala
- src/test/scala/com/ubirch/ModelCreationHelper.scala
- src/test/scala/com/ubirch/TestBase.scala
- src/test/scala/com/ubirch/db/tables/PocAdminRepositoryMock.scala
- src/test/scala/com/ubirch/db/tables/PocEmployeeRepositoryMock.scala
- src/test/scala/com/ubirch/db/tables/PocRepositoryMock.scala
- src/test/scala/com/ubirch/e2e/controllers/TenantAdminControllerSpec.scala
- src/test/scala/com/ubirch/e2e/db/PocEmployeeTableTest.scala
- src/test/scala/com/ubirch/e2e/db/PocTableTest.scala
- src/test/scala/com/ubirch/e2e/flows/PocEmployeeCreationFlowTest.scala
- src/test/scala/com/ubirch/e2e/keycloak/ResponseManagementTest.scala
- src/test/scala/com/ubirch/services/poc/PocAdminCreatorLoopTest.scala
- src/test/scala/com/ubirch/services/poc/PocAdminCreatorTest.scala
- src/test/scala/com/ubirch/services/poc/PocCreationLoopTest.scala
- src/test/scala/com/ubirch/services/poc/PocCreatorCertificateCreationTest.scala
- src/test/scala/com/ubirch/services/poc/PocCreatorTest.scala
- src/test/scala/com/ubirch/services/poc/PocEmployeeCreatorLoopTest.scala
- src/test/scala/com/ubirch/services/poc/PocEmployeeCreatorTest.scala
PoC/PoC Admin/PoC Employee loops retrieves only IDs from DB and then processes the entities one by one
> Ung 2603 proceess maximum of n elements in loops

- poc-api/Dockerfile
- poc-config-provider/Dockerfile
The application used to run as root inside the container. This
commit adds an unprivileged user, that is being used to run the
executable. This hardens the application against certain attack
vectors.
Ticket reference: UD-210
> Run as unprivileged user
